//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneYonetimSistemi.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KutuphaneYonetimiEntities : DbContext
    {
        public KutuphaneYonetimiEntities()
            : base("name=KutuphaneYonetimiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Ceza> tbl_Ceza { get; set; }
        public virtual DbSet<tbl_Kategori> tbl_Kategori { get; set; }
        public virtual DbSet<tbl_KitapEmanet> tbl_KitapEmanet { get; set; }
        public virtual DbSet<tbl_Kitaplar> tbl_Kitaplar { get; set; }
        public virtual DbSet<tbl_Personel> tbl_Personel { get; set; }
        public virtual DbSet<tbl_Uyeler> tbl_Uyeler { get; set; }
        public virtual DbSet<tbl_YayınEvi> tbl_YayınEvi { get; set; }
        public virtual DbSet<tbl_Yazar> tbl_Yazar { get; set; }
        public virtual DbSet<tbl_Yetki> tbl_Yetki { get; set; }
    }
}
