//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneYonetimSistemi.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ceza
    {
        public int Id { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public Nullable<int> KitapId { get; set; }
        public Nullable<int> KitapEmanetId { get; set; }
        public Nullable<int> GunSayisi { get; set; }
        public Nullable<decimal> CezaUcret { get; set; }
        public Nullable<int> UyeId { get; set; }
    
        public virtual tbl_KitapEmanet tbl_KitapEmanet { get; set; }
        public virtual tbl_Kitaplar tbl_Kitaplar { get; set; }
        public virtual tbl_Personel tbl_Personel { get; set; }
        public virtual tbl_Uyeler tbl_Uyeler { get; set; }
    }
}
