//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneYonetimSistemi.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KitapEmanet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_KitapEmanet()
        {
            this.tbl_Ceza = new HashSet<tbl_Ceza>();
        }
    
        public int Id { get; set; }
        public Nullable<int> KitapId { get; set; }
        public Nullable<int> UyeId { get; set; }
        public Nullable<System.DateTime> KitapVerilisTarih { get; set; }
        public Nullable<System.DateTime> KitapAlisTarih { get; set; }
        public Nullable<System.DateTime> KitapTeslim { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public Nullable<bool> Durumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ceza> tbl_Ceza { get; set; }
        public virtual tbl_Kitaplar tbl_Kitaplar { get; set; }
        public virtual tbl_Personel tbl_Personel { get; set; }
        public virtual tbl_Uyeler tbl_Uyeler { get; set; }
    }
}
