//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneYonetimSistemi.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Kitaplar()
        {
            this.tbl_Ceza = new HashSet<tbl_Ceza>();
            this.tbl_KitapEmanet = new HashSet<tbl_KitapEmanet>();
        }
    
        public int Id { get; set; }
        public string KitapAdi { get; set; }
        public Nullable<byte> Kategori { get; set; }
        public Nullable<int> Yazar { get; set; }
        public Nullable<int> YayınEvi { get; set; }
        public Nullable<short> SayfaSayısı { get; set; }
        public string BasımYılı { get; set; }
        public Nullable<short> Adet { get; set; }
        public string Aciklama { get; set; }
        public string Durumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ceza> tbl_Ceza { get; set; }
        public virtual tbl_Kategori tbl_Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KitapEmanet> tbl_KitapEmanet { get; set; }
        public virtual tbl_YayınEvi tbl_YayınEvi { get; set; }
        public virtual tbl_Yazar tbl_Yazar { get; set; }
    }
}
